#!/usr/bin/env bash

set -e

# Script & Project directories
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

cmd="$1"

case "$cmd" in
    dev)
        exec "$SCRIPT_DIR/dev"
        ;;

    edge)
        exec "$SCRIPT_DIR/edge"
        ;;

    rpi)
        exec "$SCRIPT_DIR/rpi"
        ;;

    uno_q)
        exec "$SCRIPT_DIR/uno_q"
        ;;

    rm)
        exec "$SCRIPT_DIR/rm"
        ;;

    esp)
        exec "$SCRIPT_DIR/esp"
        ;;

    *)
        echo "Usage:"
        echo "  robot dev   → start dev container"
        echo "  robot edge  → start edge container (Generic)"
        echo "  robot edge  → start edge container (Raspberry Pi)"
        echo "  robot edge  → start edge container (Arduino Uno Q)"
        echo "  robot rm    → remove container and free space"
        echo "  robot esp   → start esp container"
        ;;
esac