services:
  ros2:
    build: .
    container_name: ros2_dev_lab
    network_mode: host
    stdin_open: true
    tty: true
    ipc: host

    environment:
      ROS_DOMAIN_ID: 0
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1
      LIBGL_ALWAYS_SOFTWARE: 1

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../../:/ros2_ws

    privileged: true